default:
  n_chains: 5
  project_dir: ""
  data_dir: "data"
  out_dir: "out"
  dev_dir: "test"
  analysis_dir: "analysis"
  posterior_path: "C:/Users/John.Foster/Downloads/iterativeFits2/1_posterior"
  n_pp: 20
  n_mcmc: 500
  n_iter: 10000

hpc_test:
  project_dir: "/lustrefs/ceah/feral-swine/farm-bill"
  posterior_path: "/lustrefs/ceah/feral-swine/property-fits/iterativeFits2/1_posterior"
  dev_dir: "test"
  n_pp: 30
  n_mcmc: 1000
  n_iter: 100000

hpc_production:
  inherits: hpc_test
  dev_dir: "production"
  n_pp: 40
  n_mcmc: 1000
  n_iter: 500000
