default:
  n_chains: 5
  data_dir: "data"
  out_dir: "out"
  dev_dir: "test"
  n_pp: 20
  n_mcmc: 500
  n_iter: 1000

hpc_test:
  project_dir: "farm-bill"
  analysis_dir: "analysis"

hpc_production:
  inherits: hpc_test
  dev_dir: "production"
  n_pp: 40
  n_mcmc: 1000
  n_iter: 500000
